# Generated by Django 3.2.6 on 2021-08-18 05:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asignacion_curso', '0001_initial'),
        ('control_asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='controlasistencia',
            unique_together={('date', 'username_student', 'asignation')},
        ),
    ]
