# Generated by Django 3.2.6 on 2021-08-18 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_asistencia', '0002_alter_controlasistencia_unique_together'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='controlasistencia',
            table='control_asistencia',
        ),
    ]
