# Generated by Django 3.2.6 on 2021-08-18 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curso', '0002_alter_curso_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(default='A', max_length=1)),
                ('cycle', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curso.curso')),
                ('username_professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seccion',
                'verbose_name_plural': 'Secciones',
            },
        ),
    ]
