# Generated by Django 3.2.6 on 2021-08-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='semester',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
