# Generated by Django 3.2.6 on 2021-08-18 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seccion', '0002_seccion_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seccion',
            old_name='cycle',
            new_name='year',
        ),
    ]
