# Generated by Django 3.2.6 on 2021-08-18 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seccion', '0003_rename_cycle_seccion_year'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='seccion',
            table='section',
        ),
    ]
