# Generated by Django 3.2.6 on 2021-08-18 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seccion', '0003_rename_cycle_seccion_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seccion.seccion')),
                ('username_student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignacion de cursos',
                'verbose_name_plural': 'Asignacion de cursos',
            },
        ),
    ]
