# Generated by Django 3.2.6 on 2021-08-20 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seccion', '0001_initial'),
        ('asignacion_curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacioncurso',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seccion.seccion'),
        ),
    ]
