# Generated by Django 3.2.6 on 2021-08-23 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asignacion_curso', '0002_asignacioncurso_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacioncurso',
            name='username_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='asignacioncurso',
            unique_together={('section', 'username_student')},
        ),
    ]
