# Generated by Django 3.2.6 on 2021-08-18 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='curso',
            table='curso',
        ),
    ]
