# Generated by Django 3.2.6 on 2021-08-18 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.rol'),
        ),
    ]
