# Generated by Django 3.2.6 on 2021-08-18 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_rol_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='rol_id',
            new_name='rol',
        ),
    ]
